### ISSUE TITLE
[security] Secrets are leaked temporary

### ISSUE THREAD

**Issue by Mic92** [ryantm/age-nix#1]
The permission update is done after writing the file:

https://github.com/ryantm/age-nix/blob/202ea075cf9e75a57543478ae7efb0985b77a3df/modules/age.nix#L65

```console
$ age -d -i ./key.txt -o foo ./data.tar.gz.age
$ ls -la foo
.rw-r--r-- 1,5k joerg  1 Sep  6:52  foo
```

**Comment by ryantm** [comment]
I believe this is fixed by https://github.com/ryantm/age-nix/commit/568dede67c032d0a8f96100530306c3fecc8d4c4 but would like a second opinion.

**Comment by Mic92** [comment]
Yes this fixes it. You can make your filesystem operation atomic by creating the temporary file in the same directory and use a `mv` instead of `install`.
